config/routes.rb
Assoc::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :topics
  resources :sessions
  resources :tags
  resources :relationships, only: [:create, :destroy]
  resources :bookmarks
  resources :comments
  resources :scorings
  resources :commentscorings
  resources :suggestededits
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match '/contact', to: 'pages#contact'
  match '/about',   to: 'pages#about'
  match '/help',    to: 'pages#help'
  match '/taglist', to: 'pages#taglist'
  match '/topicdiscovery', to: 'pages#topicdiscovery'
  #match '/topiclist',    to: 'pages#topiclist'
  
  root to: 'pages#home'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :commentscorings, dependent: :destroy
  
  attr_accessible :content, :ispro, :is_anon, :topic_id
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate, only: [:create, :destroy]
  before_filter :authorized_user, only: :destroy  
  
  def create
    @comment = Comment.new(params[:comment])
    @comment.score = 1
    @comment.user_id = current_user.id
    scoring = @comment.commentscorings.build(vote: 1, user_id: current_user.id, topic_id: @comment.topic_id)
    @topic = Topic.find_by_id(@comment.topic_id)
    if @comment.save
      redirect_to @topic
    else
      redirect_to root_path
    end
  end
  
  def destroy   
    comment = Comment.find(params[:id])
    @topic = Topic.find_by_id(comment.topic_id)
    comment.destroy    
    redirect_to @topic
  end
  
  def edit
    @title = "Edit comment"
    @comment = Comment.find_by_id(params[:id])
  end
  
  def update
    @comment = Comment.find(params[:id])
    @topic = Topic.find_by_id(@comment.topic_id)
    if @comment.update_attributes(params[:comment])
      redirect_to @topic
    else
      redirect_to root
    end
  end
  
  private
  
    def authorized_user
      unless current_user.admin?
        @topic = current_user.topics.find_by_id(params[:id])
        redirect_to root_path if @topic.nil?
      end
    end
end

app/views/comments/_comment.html.erb
<% @comment = comment %>
<% if comment.ispro? %>
	<div class = "preconcommentsymbol">  </div>
	<div class="commenttitlecontainer">
		<p class = "commenttitletext"><%= comment.content %></p>
	</div>
<% else %>
	<div class="concommentscoredisplay">
		<span id="commentscoring_<%= comment.id%>" class="stat"> 
			<%= comment.score %>
	  </span>
	</div>
<% end %>

<% if comment.ispro? %>	
	<div class="procommentvotingcontainer">
<% else  %>
	<div class="concommentvotingcontainer">
<% end %>
<% unless current_user.nil? %>
	<div class = "hiddencommentvotingcontainer">	
		<%= render 'shared/upvote_comment_form'%>
		<%= render 'shared/downvote_comment_form'%>
	</div>
<% end %>
</div>

<% if !comment.ispro? %>
	<div class = "preconcommentsymbol">  </div>
	<div class="commenttitlecontainer">
		<p class = "commenttitletext"><%= comment.content %></p>
	</div>
<% end %>

<% if comment.ispro? %>
	<div class="procommentscoredisplay">
		<span id="commentscoring_<%= comment.id%>" class="stat"> 
			<%= comment.score %>
	  </span>
	</div>
<% end %>

<% if comment.ispro? %>
	<div class = "miniprocommentoptions">
<% else %>
	<div class = "miniconcommentoptions">
<% end %>
		<% subauthor = User.find_by_id(comment.user_id)%>
		<p class = "showcommentauthor"><b>Posted by: <u></b><%=link_to subauthor.name, subauthor %></u></p>
		<% if signed_in? %>	
			<% if current_user.admin? || current_user.id == @comment.user_id %>
				<p class = "showcommentedit"><b><u><%=link_to "Edit", edit_comment_path(@comment)%></u></b></p>
				<p class = "showcommentdelete"><b><u><%=link_to "Delete", comment, method: :delete, confirm: "You sure?", title: comment.content %></u></b></p>
			<% end %>
		<% end %>	
		</div>

app/views/comments/_delete.html.erb
<%= form_for @comment, html: { method: :delete } do |f| %>
  <div class="actions">	   
	<%= f.submit "Delete" %>	
  </div>

<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
	
<%= form_for(@comment) do |f| %>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>   
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>