config/routes.rb
Assoc::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :topics
  resources :sessions
  resources :tags
  resources :relationships, only: [:create, :destroy]
  resources :bookmarks
  resources :comments
  resources :scorings
  resources :commentscorings
  resources :suggestededits
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match '/contact', to: 'pages#contact'
  match '/about',   to: 'pages#about'
  match '/help',    to: 'pages#help'
  match '/taglist', to: 'pages#taglist'
  match '/topicdiscovery', to: 'pages#topicdiscovery'
  #match '/topiclist',    to: 'pages#topiclist'
  
  root to: 'pages#home'

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :topic
  acts_as_url :content
  
  attr_accessible :content, :topic_id
  
  def to_param
    url
  end
  
  def tag_content
    tag.try(:content)
  end
  
  def tag_content=(content)
    self.tag = Tag.find_or_create_by_content(content) if content.present?
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :authenticate, only: [:create, :destroy]
  before_filter :authorized_user, only: :destroy  
  
  def index
    @title = "All Tags"
    @tags = Tag.find(:all, group: "content")
    @searchtags = Tag.order(:content).where(["content like ?", "%#{params[:term]}%"])
    render json: @searchtags.map(&:content)
  end
  
  def show
    @tag = Tag.find_by_url(params[:id])
    @temp = Tag.find(:all, conditions: [ "lower(content) = ?", @tag.content.downcase])
  end
  
  def create
    @tag = Tag.new(params[:tag])
    @topic = Topic.find_by_id(@tag.topic_id)
    if Tag.find(:all, conditions: [ "lower(content) = ? and topic_id = ?", 
      @tag.content.downcase, @tag.topic_id]).count == 0
      @tag.content.capitalize!
      @tag.save
    end
    redirect_to @topic
  end
  
  def destroy   
    tag = Tag.find_by_url(params[:id])
    @topic = Topic.find_by_id(tag.topic_id)
    tag.destroy    
    redirect_to @topic
  end
  
  private
  
    def authorized_user
      unless current_user.admin?
        @topic = current_user.topics.find_by_id(params[:id])
        redirect_to root_path if @topic.nil?
      end
    end
end

app/views/tags/_search_form.html.erb
<%= form_for(@tag) do |f| %>
  <div class="field">
    <%= f.label "New tag" %><br />
    <%= f.text_field :content, data: {autocomplete_source: tags_path} %>
  </div>
  <div class="actions">
	<%= f.hidden_field :topic_id, value: @topic.id %>
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/_tag.html.erb
<div class = topic-odd >
  <%= link_to tag.content, tag %>
  <% if current_user.admin? %>
  || || <%= link_to "delete tag", tag, method: :delete, confirm: "You sure?", 
							       title: tag.content %>							
  <% end %>		
</div>

app/views/tags/index.html.erb
this page never gets called...
<div class = pagetitle>
	<%= @title %> 
</div>

<ul class="topics">
  <%= render @tags %>
</ul>

app/views/tags/new.html.erb
<h1>Add Tag</h1>

<%= form_for(@tag) do |f| %>
  <% hidden_field :topic_id, value: @topic.id %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/tags/show.html.erb
<h1>Topics tagged with "<%= @tag.content%>"</h1>

<table class= "tags" summary="all tags">
	<% @temp.each do |i| %>
		<tr>
			<td class="tag-<%= cycle("odd", "even") %>">
			<%= link_to Topic.find_by_id(i.topic_id).content, Topic.find_by_id(i.topic_id) %>	
			</td>
		</tr>				
	<% end %>
</table>