config/routes.rb
Assoc::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :topics
  resources :sessions
  resources :tags
  resources :relationships, only: [:create, :destroy]
  resources :bookmarks
  resources :comments
  resources :scorings
  resources :commentscorings
  resources :suggestededits
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match '/contact', to: 'pages#contact'
  match '/about',   to: 'pages#about'
  match '/help',    to: 'pages#help'
  match '/taglist', to: 'pages#taglist'
  match '/topicdiscovery', to: 'pages#topicdiscovery'
  #match '/topiclist',    to: 'pages#topiclist'
  
  root to: 'pages#home'

end

app/views/layouts/_header.html.erb
<header>
	<div class = "siteheader"> 
		<div class = "fusegap">
			<p> <%= link_to "fuseGap", root_path %> </p>
		</div>
		<div class = "headerlinks">
  		<div class="round">	
		    <ul>
		   <!--  <li><%= link_to "Home", root_path %></li>  -->
			  	<li><%= link_to "Topics", topics_path %></li>
		   <!--   <li><%= link_to "Tags", taglist_path %></li>  -->
				<% if signed_in? %>
			  	<li><%= link_to "Users", users_path %></li>
		      <li><%= link_to "Profile", user_path(current_user) %></li>
			  	<li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
		      <li><%= link_to "Bookmarks", bookmarks_path %></li>
		   <!--  <li><%= link_to "Topic Discovery", topicdiscovery_path %></li>  -->
		    <% end %>
		      <% if signed_in? %>
		      <li><%= link_to "Logout", signout_path, :method => :delete %></li>
		      <% else %>
		      <li><%= link_to "Sign in", signin_path %></li>
		      <% end %>
		    </ul>
		  </div>
		</div>
	</div>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
    </div>
  </body>
</html>